version: 2
jobs:
  build:
    working_directory: /home/circleci
    docker:
      - image: yikaus/alpine-bash
    steps:
      - checkout
      - restore_cache:
          key: cache_key
      - run: ./add_files /home/circleci/cached
      - run: ls -lA /home/circleci/cached
      - save_cache:
          key: cache_key
          paths:
            - /home/circleci/cached
