version: 2
jobs:
  build:
    working_directory: /home/circleci/test
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: cache_key
      - run: ./add_file.sh /home/circleci/cached
      - run: ls -lA /home/circleci/cached
      - save_cache:
          key: cache_key-{{ epoch }}
          paths:
            - /home/circleci/cached
